### ISSUE TITLE
更新apollo-kernel之后，docker 不能使用

### ISSUE THREAD

**Issue by ahuer2435** [ApolloAuto/apollo-kernel#10]
您好，
    我的使用流程如下：
    （1） 下载apollo，然后按照其中的README_cn.md步骤操作，可以正常使用，可以看到小汽车的回放运动。
    （2） 安装apollo-kernel按照其下README.md的步骤，更新kernel。 更新之前系统版本如下：
   Linux yanqiao-VirtualBox 4.4.0-93-generic #116~14.04.1-Ubuntu SMP Mon Aug 14 16:07:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
安装之后系统版本如下：
   Linux yanqiao-VirtualBox 4.4.32-apollo-1-RT #1 SMP PREEMPT RT Tue Jul 4 19:29:34 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
 然后执行docker ps提示：
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

执行ps -ef|grep docker如下：
root      7621     1  3 09:42 ?        00:00:00 /usr/bin/dockerd --raw-logs
root      7630  7621  4 09:42 ?        00:00:00 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
感觉也是正常的，但是dcoker就是不能使用，有重启过docker和电脑都不行。
为什么更新kernel之前可用，之后就不能用了，如何解决，谢谢？

然后我实在虚拟机上测试以上环境。

**Comment by quning18** [comment]
Have you tried the following instruction in our quick start?

https://github.com/ApolloAuto/apollo/blob/master/docs/quickstart/apollo_1_0_quick_start.md#set-up-docker-support

   1.

   (Optional) If you already have Docker installed (before you installed
   the Apollo Kernel), add the following line in /etc/default/docker:

DOCKER_OPTS = "-s overlay"


Best wishes,
-- 
Ning Qu

2017-09-17 18:45 GMT-07:00 ahuer2435 <notifications@github.com>:

**Comment by ahuer2435** [comment]
确实忘记了这一步骤，加上去，解决了，谢谢。
