### ISSUE TITLE
questions about ESDCAN kernel?

### ISSUE THREAD

**Issue by Wsine** [ApolloAuto/apollo-kernel#12]
some questions about this page: https://github.com/ApolloAuto/apollo-kernel/blob/master/linux/ESDCAN-README.md

1. where is `Makefile.esd` file and `Kconfig.esd` file?
2. run "./build.sh [target]", what is the target name?
3. how to use `esdcan-pcie402.ko` after built?

**Comment by startcode** [comment]
I guess you need to get ESD can driver source code by yourself. Due to license reasons, we could not directly host ESD can driver on github.

**Comment by NatureEngine** [comment]
CAN-PCIe/402
https://esd.eu/en/software-downloads/28547
