### ISSUE TITLE
Could not set Resolution of the Screen after install apollo-kernel

### ISSUE THREAD

**Issue by gengqx** [ApolloAuto/apollo-kernel#15]
I follow the step and have success install apollo-kernel ，using
```
uname -r
```
I would get 
```
4.4.32-apollo-2-RT
```
The resolution would be a fix at 800*640
the way I installed nvidia driver is by 
```
bash apollo-kernel/linux/install-nvidia.sh
```
which extract some libs of driver version 375.39
If I use
```
xrandr -q
```
I would get
```
xrandr: Failded to get size of gamma of for output default
...
```
I have try to change the default starting resolution by  modify the grub cfg.and update the grub cfg,But is still not work. How Can I solve this problem.

**Comment by quning18** [comment]
you need to install nvidia 375.39 on your taget system as well after installing apollo kernel. Let me know if you still run into similar issue.

**Comment by storypku** [comment]
Close stale issue.
