### ISSUE TITLE
Slow graphical refresh

### ISSUE THREAD

**Issue by Trelsmo** [ApolloAuto/apollo-kernel#16]
When using the 4.4.32-apollo-2-RT kernel, the graphical refresh rate is incredibly slow. Is there a way to fix this? Observe that we're running on the Nuvo-6108GC(Xeon E3-1275, graphics: Gallium 0.4 on llvmpipe) internal graphics unit and not on a separate graphics card.

Thanks in advance.

**Comment by sjtugjy** [comment]
Hi, @Trelsmo 

I meet the same problem. Have you solved it?
Even if I disable the GUI (gnome), the refresh rate is still slow (e.g., executing dmesg).

**Comment by Trelsmo** [comment]
We had Ubuntu 16.04 and when we changed to 14.04 it worked fine.
