### ISSUE TITLE
Linux 4.4内核，打了RT patch，又修了几处bug，还有啥？

### ISSUE THREAD

**Issue by rssnsj** [ApolloAuto/apollo-kernel#2]
Linux 4.4内核，打了RT patch，又修了几处bug，还有啥？

**Comment by j2eeex** [comment]
做这个项目的成员，百度应该把他们开了！纯粹糊弄李彦宏的玩意儿！

**Comment by quning18** [comment]
this is for technical discussion for specific issues. If no further details, we will close this issue for now.
