### ISSUE TITLE
how to uninstall the apollo-kernel?

### ISSUE THREAD

**Issue by Vandaci** [ApolloAuto/apollo-kernel#22]
see the title

**Comment by Vandaci** [comment]
nobody?

**Comment by quning18** [comment]
sorry, we don't provide uninstall script for this moment. However, the files and installation steps have full details in installation script. You can reverse the installation steps by reference that script.

However, if you would just need to switch over to regular kernel previously working on your machine,  the better option is to switch to the existing known kernel in grub.

**Comment by storypku** [comment]
Stale issue closed.
