### ISSUE TITLE
Makefile:1034: recipe for target 'include/generated/utsrelease.h' failed

### ISSUE THREAD

**Issue by qcqcc** [ApolloAuto/apollo-kernel#23]
我们在使用Apollo kernel 1.0.0加载esdcan编译的时候，出现找不到'include/generated/utsrelease.h'这个文件错误。如何解决？

我们下载了linux-4.4.32-apollo-1.0.0.tar.gz发现里面有这个文件。
这个压缩包中包含esdcan吗？

**Comment by quning18** [comment]
不包括esdcan, esdcan需要单独到其公司网站申请下载
