### ISSUE TITLE
18.04cannot install nvidia'driver

### ISSUE THREAD

**Issue by pjs9115916** [ApolloAuto/apollo-kernel#26]
I fellow the steps of readme to install the driver of NVIDIA 1080, but  it always inform me "Failed to initialize NVML: Driver/library version mismatch"  .
My ubuntu is 18.04 and the readme link as follow:
https://github.com/ApolloAuto/apollo-kernel/blob/master/linux/Install_nvidia_driver_on_ubuntu_18.04.md

thank you so much

**Comment by pjs9115916** [comment]
and I think maybe there is a mistake in the readme,becausewhen  I use "cat /proc/driver/nvidia/version"to check ,it is recomend  "NVIDIA UNIX x86_64 Kernel Module  375.39 ", but the readme recomend to install 430.

**Comment by pjs9115916** [comment]
when I install the driver 430, a error occured "ERROR (dkms apport): kernel package linux-headers-4.4.32-apollo-2-RT is not supported
Error! Bad return status for module build on kernel: 4.4.32-apollo-2-RT (x86_64)
"

**Comment by storypku** [comment]
Please refer to https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md on how to install low-latency/realtime kernel together with Nvidia driver.
