### ISSUE TITLE
The problem about downloading the linux-4.4.32-apollo-1.5.5.tar.gz

### ISSUE THREAD

**Issue by yangyunfei16** [ApolloAuto/apollo-kernel#27]
Why did I get stuck when I only downloaded about tens of KB when downloading the linux-4.4.32-apollo-1.5.5.tar.gz?

**Comment by storypku** [comment]
Hi @yangyunfei16, please check your Internet connection and try again.

FYI, you can refer to https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md
on how to install Ubuntu low-latency/realtime kernel in the vehicle.
