### ISSUE TITLE
linux-4.4.32-apollo-1.5.5.tar.gz

### ISSUE THREAD

**Issue by wangzhongchuan1973** [ApolloAuto/apollo-kernel#28]
The files can't be downloaded 
linux-4.4.32-apollo-1.5.5.tar.gz

**Comment by storypku** [comment]
Hi @wangzhongchuan1973 , please check your Internet connection. 
FYI, please refer to https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md
on how to install Ubuntu low-latency/realtime kernel in the vehicle.
