### ISSUE TITLE
apollo-kernel and its suported Ubuntu version.

### ISSUE THREAD

**Issue by hongyi-zhao** [ApolloAuto/apollo-kernel#29]
Hi,

I'm confused on the following problems:

1. Can I run apollo use the ogrinal linux kernel shipped with Ubuntu without installation of apollo-kernel?
2. What's the latest Ubuntu version supported by the current apollo-kernel?

**Comment by storypku** [comment]
=> https://github.com/ApolloAuto/apollo/issues/11739
