### ISSUE TITLE
Support for Nvidia >= 440 Driver

### ISSUE THREAD

**Issue by agarwalsid** [ApolloAuto/apollo-kernel#30]
Hi,

Apollo 5.5 recently transitioned to Cuda 10.2 and Nvidia Driver >=440. Is it possible to upgrade the Apollo kernel with this change?

**Comment by storypku** [comment]
Hi @agarwalsid, it seems that this project wasn't actively maintained, you can refer to https://github.com/ApolloAuto/apollo/blob/master/docs/howto/how_to_install_apollo_kernel.md on how to install low-latency/realtime kernel with latest Nvidia driver.

**Comment by storypku** [comment]
Hi @agarwalsid, I am closing this issue now. If you have other questions, please feel free to open another issue. Or reopen this one if the problem persists.
