### ISSUE TITLE
是否要安装Apollo Kernel

### ISSUE THREAD

**Issue by hfr2015** [ApolloAuto/apollo-kernel#33]
ubuntu18.04，内核5.4.0-53-generic，是否需要安装Apollo Kernel

**Comment by zhonghuarenmingongheguo** [comment]
需要

**Comment by hfr2015** [comment]
您好，那我也是安装apollo kernel 基于4.4.32内核的安装包么，这样的话会不会和5.4.0-53-generic有冲突啥的

**Comment by zhonghuarenmingongheguo** [comment]
对的

发件人: gaorui ***@***.***>
发送时间: 2021年6月28日 14:55
收件人: ApolloAuto/apollo-kernel ***@***.***>
抄送: 赵国庆 ***@***.***>; Comment ***@***.***>
主题: Re: [ApolloAuto/apollo-kernel] 是否要安装Apollo Kernel (#33)


您好，那我也是安装apollo kernel 基于4.4.32内核的安装包么

―

**Comment by hfr2015** [comment]
好的好的，多谢~

**Comment by zhonghuarenmingongheguo** [comment]
客气

发件人: gaorui ***@***.***>
发送时间: 2021年6月28日 15:11
收件人: ApolloAuto/apollo-kernel ***@***.***>
抄送: 赵国庆 ***@***.***>; Comment ***@***.***>
主题: Re: [ApolloAuto/apollo-kernel] 是否要安装Apollo Kernel (#33)


好的好的，多谢~

―
