### ISSUE TITLE
prebuild kernel would not support nvidia driver?

### ISSUE THREAD

**Issue by niise** [ApolloAuto/apollo-kernel#6]
here is the docker.log

#sudo vim /var/log/upstart/docker.log
/var/run/docker.sock is up
time="2017-07-17T10:30:16.842745248+08:00" level=info msg="libcontainerd: new containerd process, pid: 13409"
time="2017-07-17T10:30:17.844303739+08:00" level=warning msg="failed to rename /var/lib/docker/tmp for background deletion: %!s(<nil>). Deleting synchronously"
time="2017-07-17T10:30:17.847192458+08:00" level=error msg="[graphdriver] prior storage driver aufs failed: driver not supported"
Error starting daemon: error initializing graphdriver: driver not supported

------------------------
I cant run docker under this kernel with nVidia GTX 970
any suggestion?

**Comment by journey-wang** [comment]
Apollo kernel currently didn't support aufs,  you can use overlayfs instead.
1. add  `DOCKER_OPTS="--storage-driver=overlay" ` in /etc/default/docker configuration file.
2. restart docker

**Comment by quning18** [comment]
Closed for inactive questions.

Please reopen it if you have any further questions. Thanks!
