### ISSUE TITLE
linux kernel hugpage config problem

### ISSUE THREAD

**Issue by Wsine** [ApolloAuto/apollo-kernel#7]
i use `vimdiff config.4.4.32 config.4.4.32.rt` to see what is the difference between them. 

i found config.rt removed `CONFIG_TRANSPARENT_HUGEPATH=y` around line 526.

```
$ diff config.4.4.32 config.4.4.32.rt
526,528d518
< CONFIG_TRANSPARENT_HUGEPAGE=y
< CONFIG_TRANSPARENT_HUGEPAGE_ALWAYS=y
< # CONFIG_TRANSPARENT_HUGEPAGE_MADVISE is not set
```

i want to know the reason for removing this config option.

looking forward to your answer, thank you.

**Comment by quning18** [comment]
That is removed because of the rt preempt patch.

**Comment by quning18** [comment]
Closed for inactive questions.

Please reopen it if you have any further questions. Thanks!
